# A program to accept any city name from user and display the monuments of that city.
print('List of cities :-')
print()
print('1) Agra')
print('2) Delhi')
print('3) Kolkata')
print('4) Lucknow')
print('5) Ahmedabad')
print('6) Jaipur')
print('7) Jammu')
print()
a=int(input('Enter the serial number of the city which you want : '))
while True:
    if a==1:
        print()
        print('Agra')
        print('1) Taj Mahal')
        print('2) Agra Fort')
        print('3) Shish Mahal (The Glass Palace)')
        print('4) Tomb of Akbar')
        print('5) Itimah-ud-Daula Tomb')
    elif a==2:
        print()
        print('Delhi')
        print('1) Red Fort')
        print('2) Qutub Minar')
        print('3) India Gate')
        print('4) Rashtrapati Bhavan')
        print('5) Jama Masjid')
    elif a==3:
        print()
        print('Kolkata')
        print('1) Indian National Army Memorial')
        print('2) Black Hole Monument')
        print('3) Indian Museum')
        print('4) Queen Victoria Statue')
        print('5) Kolkata Time Zone Clock Tower')
    elif a==4:
        print()
        print('Lucknow')
        print('1) Baradari')
        print('2) Shaheed Smarak')
        print('3) Ghanta Ghar')
        print('4) British Residency')
        print('5) Tomb of Saadat Ali Khan')
    elif a==5:
        print()
        print('Ahmedabad')
        print('1) Statue of Unity')
        print('2) Lal Darwaza')
        print('3) Bhadra Fort')
        print('4) World Vintage Car Museum')
        print('5) Raksha Shakti University')
    elif a==6:
        print()
        print('Jaipur')
        print('1) Amar Jawan Jyoti')
        print('2) Chandpole Gate')
        print('3) Sisoda Rani ka Bagh')
        print('4) Gaitore ki Chhatriyan')
        print('5) Bhan Garh Fort')
    elif a==7:
        print()
        print('Jammu')
        print('1) Hari Parbat Fort')
        print('2) Bahu Fort')
        print('3) Akhnoor Fort')
        print('4) Poonch Fort')
        print('5) Peerkho Caves')
    else:
        print()
        print('❎ Wrong Input, Enter number from 1 to 7')
    print()
    a=int(input("Enter another city : "))
